# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingFileTypeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[(b'shapefile', b'shapefile'), (b'tabular', b'tabular'), (b'geotiff', b'geotiff')], max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('inactive_display_note', models.TextField(blank=True, help_text=b'Displayed on landing page if the IncomingFileType is not active')),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RegisteredDataverse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dataverse_url', models.URLField(help_text=b'No trailing slash. Examples: "http://dvn-build.hmdc.harvard.edu", "https://dataverse-demo.iq.harvard.edu"', unique=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text=b'optional')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
