
STEP1_EXAMINE = '1. Visualize Shapefile'
STEP2_VISUALIZE = '1. Visualize the Shapefile'
STEP3_STYLE = '2. Style Map Layer'

#GEOCONNECT_STEPS = (STEP1_EXAMINE, STEP2_VISUALIZE, STEP3_STYLE)
GEOCONNECT_STEPS = (STEP1_EXAMINE, STEP3_STYLE)

GEOCONNECT_STEP_KEY = 'GEOCONNECT_STEP_KEY'