
STEP1_EXAMINE = '1. Map Dataverse File'
STEP2_STYLE = '2. Style Map'

GEOCONNECT_STEPS = (STEP1_EXAMINE, STEP2_STYLE)

GEOCONNECT_STEP_KEY = 'GEOCONNECT_STEP_KEY'

PANEL_TITLE_MAP_DATA_FILE = 'Map Data File'
PANEL_TITLE_STYLE_MAP = 'Style Map'
