
# Used when initially retrieving Dataverse information
#
FAILED_TO_RETRIEVE_DATAVERSE_FILE = 'FAILED_TO_RETRIEVE_DATAVERSE_FILE'
FAILED_TO_CONVERT_RESPONSE_TO_JSON = 'FAILED_TO_CONVERT_RESPONSE_TO_JSON'
FAILED_BAD_STATUS_CODE_FROM_WORLDMAP = 'FAILED_BAD_STATUS_CODE_FROM_WORLDMAP'
FAILED_TO_IDENTIFY_METADATA_MAPPING_TYPE = 'FAILED_TO_IDENTIFY_METADATA_MAPPING_TYPE'

# Used for evaluating a zipped Shapefile
#
ZIPCHECK_NO_SHAPEFILES_FOUND = 'ZIPCHECK_NO_SHAPEFILES_FOUND'
ZIPCHECK_MULTIPLE_SHAPEFILES = 'ZIPCHECK_MULTIPLE_SHAPEFILES'
ZIPCHECK_NO_FILE_TO_CHECK = 'ZIPCHECK_NO_FILE_TO_CHECK'
ZIPCHECK_FAILED_TO_PROCCESS_SHAPEFILE = 'ZIPCHECK_FAILED_TO_PROCCESS_SHAPEFILE'
