# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis_basic_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapefileInfo',
            fields=[
                ('gisdatafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gis_basic_file.GISDataFile')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('zipfile_checked', models.BooleanField(default=False)),
                ('has_shapefile', models.BooleanField(default=False)),
                ('number_of_features', models.IntegerField(default=0)),
                ('bounding_box', models.CharField(blank=True, max_length=255)),
                ('column_names', jsonfield.fields.JSONField(blank=True, help_text=b'Saved as a json list')),
                ('column_info', jsonfield.fields.JSONField(blank=True, help_text=b'Includes column type, field length, and decimal length. Saved as a json list.')),
                ('extracted_shapefile_load_path', models.CharField(blank=True, help_text=b'Used to load extracted shapefile set', max_length=255)),
            ],
            options={
                'ordering': ('-modified', 'datafile_label'),
                'verbose_name': 'Shapefile Information',
                'verbose_name_plural': 'Shapefile Information',
            },
            bases=('gis_basic_file.gisdatafile',),
        ),
        migrations.CreateModel(
            name='WorldMapShapefileLayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('layer_name', models.CharField(blank=True, help_text=b'auto-filled on save', max_length=255)),
                ('core_data', jsonfield.fields.JSONField()),
                ('attribute_data', jsonfield.fields.JSONField()),
                ('download_links', jsonfield.fields.JSONField(blank=True)),
                ('md5', models.CharField(blank=True, db_index=True, help_text=b'auto-filled on save', max_length=40)),
                ('shapefile_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_shapefiles.ShapefileInfo')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'WorldMapShapefileLayerInfo',
                'verbose_name_plural': 'WorldMapShapefileLayerInfo',
            },
        ),
    ]
