# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:44
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis_basic_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabularFileInfo',
            fields=[
                ('gisdatafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gis_basic_file.GISDataFile')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('delimiter', models.CharField(default=b'\t', max_length=10)),
                ('is_file_readable', models.BooleanField(default=False)),
                ('num_rows', models.IntegerField(default=0)),
                ('num_columns', models.IntegerField(default=0)),
                ('column_names', jsonfield.fields.JSONField(blank=True, help_text=b'Saved as a json list')),
                ('has_header_row', models.BooleanField(default=True)),
                ('chosen_column', models.CharField(blank=True, max_length=155)),
                ('dv_join_file', models.FileField(blank=True, help_text=b'Used when a new column needs to be added for a TableJoin', max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/Users/rmp553/Documents/iqss-git/geoconnect/test_setup/dv_datafile_directory'), upload_to=b'dv_files/join/%Y/%m/%d')),
            ],
            options={
                'ordering': ('-modified', 'datafile_label'),
                'verbose_name': 'Tabular File Information',
                'verbose_name_plural': 'Tabular File Information',
            },
            bases=('gis_basic_file.gisdatafile',),
        ),
        migrations.CreateModel(
            name='TestIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('column_names', jsonfield.fields.JSONField(blank=True, help_text=b'Saved as a json list')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorldMapJoinLayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('layer_name', models.CharField(blank=True, help_text=b'auto-filled on save', max_length=255)),
                ('core_data', jsonfield.fields.JSONField()),
                ('attribute_data', jsonfield.fields.JSONField()),
                ('download_links', jsonfield.fields.JSONField(blank=True)),
                ('md5', models.CharField(blank=True, db_index=True, help_text=b'auto-filled on save', max_length=40)),
                ('join_description', models.TextField(blank=True)),
                ('tabular_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_tabular.TabularFileInfo')),
            ],
            options={
                'verbose_name': 'WorldMap Tabular Join Layer Information',
                'verbose_name_plural': 'WorldMap Tabular Join Layer Information',
            },
        ),
        migrations.CreateModel(
            name='WorldMapLatLngInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('layer_name', models.CharField(blank=True, help_text=b'auto-filled on save', max_length=255)),
                ('core_data', jsonfield.fields.JSONField()),
                ('attribute_data', jsonfield.fields.JSONField()),
                ('download_links', jsonfield.fields.JSONField(blank=True)),
                ('md5', models.CharField(blank=True, db_index=True, help_text=b'auto-filled on save', max_length=40)),
                ('tabular_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_tabular.TabularFileInfo')),
            ],
            options={
                'verbose_name': 'WorldMap Latitude/Longitude Layer Information',
                'verbose_name_plural': 'WorldMap Latitude/Longitude Layer Information',
            },
        ),
    ]
