# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default=b'Maintenance Mode', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, help_text=b'Message to Display on Page.  When available, displayed instead of a template.')),
                ('template_name', models.CharField(default=b'content_pages/maintenance_message.html', help_text=b'Template with HTML snippet to display.  Note: This field is ignored if a "message" is available.', max_length=255)),
                ('end_datetime', models.DateTimeField(blank=True, help_text=b'End datetime to display within the template. Important: Maintenance mode NEEDS TO BE TURNED OFF *manually*.  This date/time is for display purposes only.', null=True)),
            ],
            options={
                'db_table': 'content_pages',
                'verbose_name_plural': 'Maintenance Mode',
            },
        ),
    ]
