# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis_basic_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinningAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StyleLayerDescriptionInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('chosen_column', models.CharField(max_length=255)),
                ('number_of_bins', models.IntegerField(default=0)),
                ('color_range_start', models.CharField(blank=True, max_length=30)),
                ('color_range_stop', models.CharField(blank=True, max_length=30)),
                ('md5', models.CharField(blank=True, db_index=True, max_length=40)),
                ('binning_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='style_layer_information.BinningAlgorithm')),
                ('gis_data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_basic_file.GISDataFile')),
            ],
            options={
                'verbose_name': 'Style layer description information',
                'verbose_name_plural': 'Style layer description information',
            },
        ),
    ]
